### ISSUE TITLE
Make the repo public and move it to Monarch's organization

### ISSUE THREAD

**Issue by ielis** [Ale-pinto-alba/utrfx#6]
It is probably better to make the repo public and move it to monarch's organization.

Making the repo public allows us to set up Github workflows for free - Github does not charge for CPU for public repositories. Moreover, we can also create draft PRs in public repos, to include code that is still a work in progress. The example workflows include continuous integration (CI) to ensure all new code passes the existing tests, and documentation deployments (when we get there). I can set these up when the time is right.

Moving to Monarch will enable other team members to contribute to the project.

@Ale-pinto-alba please move the repo and make it public.

**Comment by Ale-pinto-alba** [comment]
I made it public and tried to transfer ownership to Monarch, but I don't have permission to create public repos in Monarch.

**Comment by Ale-pinto-alba** [comment]
Should I make it private again and transfer it to Monarch? So, then, the admin can make it public.

**Comment by ielis** [comment]
Ah, OK. So let's just keep it public on your profile. Public = no issues as far as I can see.. :)
